### ISSUE TITLE
Drop older node versions from `engines.node` (align with ESLint 9?)

### ISSUE THREAD

**Issue by voxpelli** [eslint-community/eslint-utils#232]
To keep up to date with our dependencies (#231, #228, #226, #222, #199) and to enable us to use modern JS features (https://github.com/eslint-community/eslint-utils/pull/204#issuecomment-2041457832) I would suggest that we align with ESLint 9's engine range, [^18.18.0 || ^20.9.0 || >=21.1.0](https://github.com/eslint/eslint/blob/6d4484d9c19e4132f3dee948174a543dbbb5d30f/package.json#L199), for the next major release.

As I mention in https://github.com/eslint-community/eslint-utils/pull/204#issuecomment-2041457832, but haven't gotten any feedback on, I would like to address this issue before spending time on undoing modern JS to something old only to have us drop the old engines right afterwards.

**Comment by scagood** [comment]
I am completely in favour of aligning with eslint's supported version ranges :+1:

We have already made the change in `eslint-plugin-n` (https://github.com/eslint-community/eslint-plugin-n/pull/161)

**Comment by MichaelDeBoey** [comment]
Closed by #242
