### ISSUE TITLE
Update Dependencies to modern versions

### ISSUE THREAD

**Issue by Byron2016** [eslint-community/eslint-utils#237]
Last update of  `eslint-community/eslint-utils` was published **2 years ago** ⏳ then most of dependencies are outdated 👨‍🦳

Is it possible to update them to **new versions** 👶👇?

| Dependency    | Current Version | Update to |
| ---------------- | ----------------- |-------------- |
|eslint-visitor-keys |  ^3.4.3   | ^4.1.0 |
| @eslint-community/eslint-plugin-mysticatea |  ^15.2.0    | ^15.6.1 |
| c8 |  ^7.12.0   |  **^10.1.2**  |
| dot-prop |  ^6.0.1   |  **^9.0.0**  |
|  eslint |  ^8.28.0   |  ^8.57.1   |
|  mocha | ^9.2.2 | **^10.7.3** |
| prettier |  2.8.4 | **3.3.3** |
| rimraf | ^3.0.2 | **^6.0.1** |
| rollup | ^2.79.1 | **^4.24.0** |
| semver | ^7.3.8 | ^7.6.3 |
| vitepress | ^1.0.0-alpha.40 | **^1.4.1** |

**Comment by MichaelDeBoey** [comment]
Closed by #238

**Comment by nathanmmiller** [comment]
Can we reopen this? eslint-visitor-keys was never updated, so it's still on v3 and not v4. @MichaelDeBoey

**Comment by mahnunchik** [comment]
Can `eslint-visitor-keys` be updated?
